# Generated by Django 4.1.7 on 2023-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('meat', 'Meat'), ('dairy', 'Dairy'), ('eggs', 'Eggs'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('pasta', 'Pasta'), ('drinks', 'Drinks'), ('fats', 'Fats'), ('breadstuff', 'Breadstuff'), ('nuts', 'Nuts'), ('fish', 'Fish'), ('mushrooms', 'Mushrooms'), ('misc', 'Misc')], max_length=50)),
                ('proteins', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('kcal', models.FloatField()),
            ],
        ),
    ]
