# Generated by Django 4.1.7 on 2023-04-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.FloatField(verbose_name='Carbs per 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(verbose_name='Fats per 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal',
            field=models.FloatField(verbose_name='Kcal per 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(verbose_name='Proteins per 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('meat', 'Meat'), ('dairy', 'Dairy'), ('eggs', 'Eggs'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('pasta', 'Pasta/Grains'), ('drinks', 'Drinks'), ('fats', 'Fats'), ('breadstuff', 'Breadstuff'), ('nuts', 'Nuts'), ('fish', 'Fish'), ('mushrooms', 'Mushrooms'), ('misc', 'Misc')], max_length=50),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50)),
                ('type', models.CharField(choices=[('breakfast', 'Breakfast'), ('second_breakfast', 'Second Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('supper', 'Supper'), ('misc', 'Misc')], max_length=50)),
                ('weight', models.FloatField()),
                ('product', models.ManyToManyField(related_name='meals', to='meals.product')),
            ],
        ),
    ]
