# Generated by Django 4.1.7 on 2023-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_product_carbs_alter_product_fats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day',
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50)),
                ('meals', models.ManyToManyField(to='meals.meal')),
            ],
        ),
    ]
