# Generated by Django 4.1.7 on 2023-04-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_meal_day_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meals',
        ),
        migrations.AddField(
            model_name='day',
            name='meals',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
    ]
