# Generated by Django 4.1.7 on 2023-03-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='tag',
            field=models.CharField(choices=[('', 'Select Tag'), ('food', 'Food'), ('transport', 'Transport'), ('bills', 'Bills'), ('fees', 'Fees'), ('misc', 'Misc')], max_length=50),
        ),
    ]
