# Generated by Django 4.1.7 on 2023-03-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_expence_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='tag',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('bills', 'Bills'), ('fees', 'Fees'), ('misc', 'Misc')], max_length=50),
        ),
    ]
