# Generated by Django 4.1.7 on 2023-03-20 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_expence_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
