# Generated by Django 4.1.7 on 2023-03-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_expence_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expence',
            new_name='Expense',
        ),
    ]
